### ISSUE TITLE
error to connecting to backend in chat feather

### ISSUE THREAD

**Issue by esradev** [LearnWebCode/react-course#6]
i got bellow error: 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘http://localhost:8080/socket.io/?EIO=3&transport=polling&t=NWqO4G7’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).

after submiting message
![1](https://user-images.githubusercontent.com/54488598/111108574-673ed580-856e-11eb-84f4-6f567e151ee1.jpg)
 in chat.

**Comment by hosseinshekofteh** [comment]
> i got bellow error:
> 
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘[http://localhost:8080/socket.io/?EIO=3&transport=polling&t=NWqO4G7’](http://localhost:8080/socket.io/?EIO=3&transport=polling&t=NWqO4G7%E2%80%99). (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).
> 
> after submiting message
> ![1](https://user-images.githubusercontent.com/54488598/111108574-673ed580-856e-11eb-84f4-6f567e151ee1.jpg)
> in chat.

 the problem fixed by updating socket.io-client and socket.io (in backend) to lastest version.

**Comment by esradev** [comment]
the problem fixed by updating socket.io-client and socket.io (in backend) to lastest version.
